name: Build and Publish

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    env:
      SolutionName: SIT.Controller
      CSProj: SIT.Controller.csproj
      Platform: 'win-x64'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Update version number
        id: update-version
        run: |
          $version = (Get-Content -Path $env:CSProj -Raw) -replace '<Version>.*<\/Version>', "<Version>1.0.${{ github.run_number }}<\/Version>"
          Set-Content -Path $env:CSProj -Value $version
          echo "Updated version is: 1.0.${{ github.run_number }}"

      - name: Restore dependencies
        run: dotnet restore ${{ env.CSProj }}

      - name: Build release
        run: dotnet build ${{ env.CSProj }} -c Release

      - name: Publish release
        run: dotnet publish ${{ env.CSProj }} -c Release -r ${{ env.Platform }} --self-contained -o publish

      - name: Get version from DLL
        id: extract-version
        run: |
          $version = [System.Diagnostics.FileVersionInfo]::GetVersionInfo("publish/SIT.Controller.dll").ProductVersion
          echo "::set-output name=VERSION::$version"

      - name: Zip published files
        run: Compress-Archive -Path publish/* -DestinationPath SIT.Controller.zip

      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: SIT.Controller
          path: SIT.Controller.zip

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.extract-version.outputs.VERSION }}
          generate_release_notes: true
          name: SIT.Controller-${{ env.Platform }}-${{ steps.extract-version.outputs.VERSION }}
          draft: true
          files: SIT.Controller.zip
