name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build release
        run: dotnet build -c Release

      - name: Publish release
        run: dotnet publish -c Release -f net7.0 -o publish

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: published-files
          path: publish
